name: ICP Canister Build, Test & Deploy

on:
  push:
    branches: [master]

jobs:
  #release build ICP canister using cargo for target wasm32-unknown-unknown
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          override: true
      - name: Adding toolchain
        run: rustup target add wasm32-unknown-unknown
      - name: Adding target
        run: rustc --print target-list
      - name: Get package name
        run: echo "package_name=$(basename "${PWD}")-backend" >> $GITHUB_ENV
      - name: Build ICP canister
        run: cargo build --release --target wasm32-unknow-unknow --package ${{ env.package_name }}