name: ICP Canister Build, Test & Deploy

on:
  push:
    branches: [master]

jobs:
  #release build ICP canister using cargo for target wasm32-unknown-unknown
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses:  actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          cache: true
      - name: Adding target
        run: rustup target add wasm32-unknown-unknown
      - name: Installing candid-extractor
        run: cargo install candid-extractor
      - name: Get package name
        run: echo "package_name=$(basename "${PWD}")-backend" >> $GITHUB_ENV
      - name: Build ICP canister
        run: cargo build --release --target wasm32-unknown-unknown --package ${{ env.package_name }}
      - name: Generating candid files
        run: candid-extractor "target/wasm32-unknown-unknown/release/canister_rust_backend.wasm" > "src/${{ env.package_name }}/${{ env.package_nam }}.did"

  deploy:
    # Deploying canister to ic network
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Import identity
        env:
          IDENTITY: ${{ secrets.IDENTITY }}
        run: |
          echo $IDENTITY base64 -d > ./identity.pem
          sed -i 's/\\r\\n/\r\n/g' ./identity.pem
          dfx identity import simson ./identity.pem
      - name: Deploy
        run: dfx deploy --ic
    
